---
name: Frontend

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_FRONTEND_DEPLOY_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 cp frontend/index.html s3://lj-train-spotting/index.html
          aws s3 cp frontend/script.js s3://lj-train-spotting/script.js
          aws s3 cp frontend/style.css s3://lj-train-spotting/style.css
          aws s3 sync frontend/assets/ s3://lj-train-spotting/assets/ --delete
